ES/Controllers/FreguesiasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ES_TP_EF;

//test daniel

namespace ES.Controllers
{
    public class FreguesiasController : Controller
    {
        private estp2Entities db = new estp2Entities();

        //espero que esta bosta funcione
        // GET: Freguesias
        public ActionResult Index()
        {
            return View(db.Freguesia.ToList());
        }

        // GET: Freguesias/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Freguesia freguesia = db.Freguesia.Find(id);
            if (freguesia == null)
            {
                return HttpNotFound();
            }
            return View(freguesia);
        }

        // GET: Freguesias/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Freguesias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "cod_postal,nome,morada")] Freguesia freguesia)
        {
            if (ModelState.IsValid)
            {
                db.Freguesia.Add(freguesia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(freguesia);
        }

        // GET: Freguesias/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Freguesia freguesia = db.Freguesia.Find(id);
            if (freguesia == null)
            {
                return HttpNotFound();
            }
            return View(freguesia);
        }

        // POST: Freguesias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "cod_postal,nome,morada")] Freguesia freguesia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(freguesia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(freguesia);
        }

        // GET: Freguesias/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Freguesia freguesia = db.Freguesia.Find(id);
            if (freguesia == null)
            {
                return HttpNotFound();
            }
            return View(freguesia);
        }

        // POST: Freguesias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Freguesia freguesia = db.Freguesia.Find(id);
            db.Freguesia.Remove(freguesia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ES/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ES_TP_EF;

namespace ES.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (Session["usuarioLogadoID"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Utilizador u)
        {
            // esta action trata o post (login)
            if (ModelState.IsValid) //verifica se é válido
            {
                using (estp2Entities dc = new estp2Entities())
                {
                    var v = dc.Utilizador.Where(a => a.username.Equals(u.username) && a.password.Equals(u.password)).FirstOrDefault();
                    if (v != null)
                    {
                        Session["usuarioLogadoID"] = v.id.ToString();
                        Session["nomeUsuarioLogado"] = v.nome.ToString();
                        return RedirectToAction("Index");
                    }
                }
            }
            return View(u);
        }
    }
}

ES/Controllers/UtilizadorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ES_TP_EF;

namespace ES.Controllers
{
    public class UtilizadorsController : Controller
    {
        private estp2Entities db = new estp2Entities();

        // GET: Utilizadors
        public ActionResult Index()
        {
            var utilizador = db.Utilizador.Include(u => u.Agendamento).Include(u => u.Agendamento1).Include(u => u.Declaracao).Include(u => u.Freguesia).Include(u => u.Pedido_Declaracao).Include(u => u.Pedido_Esclarecimento).Include(u => u.Pedido_Esclarecimento1).Include(u => u.Reportar_Problema).Include(u => u.Reportar_Problema1).Include(u => u.Sugestao);
            return View(utilizador.ToList());
        }

        // GET: Utilizadors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilizador utilizador = db.Utilizador.Find(id);
            if (utilizador == null)
            {
                return HttpNotFound();
            }
            return View(utilizador);
        }

        // GET: Utilizadors/Create
        public ActionResult Create()
        {
            ViewBag.id = new SelectList(db.Agendamento, "id", "objetivo");
            ViewBag.id = new SelectList(db.Agendamento, "id", "objetivo");
            ViewBag.id = new SelectList(db.Declaracao, "id", "descricao");
            ViewBag.cod_postal = new SelectList(db.Freguesia, "cod_postal", "nome");
            ViewBag.id = new SelectList(db.Pedido_Declaracao, "id", "descricacao");
            ViewBag.id = new SelectList(db.Pedido_Esclarecimento, "id", "descricao");
            ViewBag.id = new SelectList(db.Pedido_Esclarecimento, "id", "descricao");
            ViewBag.id = new SelectList(db.Reportar_Problema, "id", "descricao");
            ViewBag.id = new SelectList(db.Reportar_Problema, "id", "descricao");
            ViewBag.id = new SelectList(db.Sugestao, "id_user", "descricao");
            return View();
        }

        // POST: Utilizadors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,cod_postal,nome,cc,n_eleitor,email,username,password,contacto")] Utilizador utilizador)
        {
            if (ModelState.IsValid)
            {
                db.Utilizador.Add(utilizador);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id = new SelectList(db.Agendamento, "id", "objetivo", utilizador.id);
            ViewBag.id = new SelectList(db.Agendamento, "id", "objetivo", utilizador.id);
            ViewBag.id = new SelectList(db.Declaracao, "id", "descricao", utilizador.id);
            ViewBag.cod_postal = new SelectList(db.Freguesia, "cod_postal", "nome", utilizador.cod_postal);
            ViewBag.id = new SelectList(db.Pedido_Declaracao, "id", "descricacao", utilizador.id);
            ViewBag.id = new SelectList(db.Pedido_Esclarecimento, "id", "descricao", utilizador.id);
            ViewBag.id = new SelectList(db.Pedido_Esclarecimento, "id", "descricao", utilizador.id);
            ViewBag.id = new SelectList(db.Reportar_Problema, "id", "descricao", utilizador.id);
            ViewBag.id = new SelectList(db.Reportar_Problema, "id", "descricao", utilizador.id);
            ViewBag.id = new SelectList(db.Sugestao, "id_user", "descricao", utilizador.id);
            return View(utilizador);
        }

        // GET: Utilizadors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilizador utilizador = db.Utilizador.Find(id);
            if (utilizador == null)
            {
                return HttpNotFound();
            }
            ViewBag.id = new SelectList(db.Agendamento, "id", "objetivo", utilizador.id);
            ViewBag.id = new SelectList(db.Agendamento, "id", "objetivo", utilizador.id);
            ViewBag.id = new SelectList(db.Declaracao, "id", "descricao", utilizador.id);
            ViewBag.cod_postal = new SelectList(db.Freguesia, "cod_postal", "nome", utilizador.cod_postal);
            ViewBag.id = new SelectList(db.Pedido_Declaracao, "id", "descricacao", utilizador.id);
            ViewBag.id = new SelectList(db.Pedido_Esclarecimento, "id", "descricao", utilizador.id);
            ViewBag.id = new SelectList(db.Pedido_Esclarecimento, "id", "descricao", utilizador.id);
            ViewBag.id = new SelectList(db.Reportar_Problema, "id", "descricao", utilizador.id);
            ViewBag.id = new SelectList(db.Reportar_Problema, "id", "descricao", utilizador.id);
            ViewBag.id = new SelectList(db.Sugestao, "id_user", "descricao", utilizador.id);
            return View(utilizador);
        }

        // POST: Utilizadors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,cod_postal,nome,cc,n_eleitor,email,username,password,contacto")] Utilizador utilizador)
        {
            if (ModelState.IsValid)
            {
                db.Entry(utilizador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id = new SelectList(db.Agendamento, "id", "objetivo", utilizador.id);
            ViewBag.id = new SelectList(db.Agendamento, "id", "objetivo", utilizador.id);
            ViewBag.id = new SelectList(db.Declaracao, "id", "descricao", utilizador.id);
            ViewBag.cod_postal = new SelectList(db.Freguesia, "cod_postal", "nome", utilizador.cod_postal);
            ViewBag.id = new SelectList(db.Pedido_Declaracao, "id", "descricacao", utilizador.id);
            ViewBag.id = new SelectList(db.Pedido_Esclarecimento, "id", "descricao", utilizador.id);
            ViewBag.id = new SelectList(db.Pedido_Esclarecimento, "id", "descricao", utilizador.id);
            ViewBag.id = new SelectList(db.Reportar_Problema, "id", "descricao", utilizador.id);
            ViewBag.id = new SelectList(db.Reportar_Problema, "id", "descricao", utilizador.id);
            ViewBag.id = new SelectList(db.Sugestao, "id_user", "descricao", utilizador.id);
            return View(utilizador);
        }

        // GET: Utilizadors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilizador utilizador = db.Utilizador.Find(id);
            if (utilizador == null)
            {
                return HttpNotFound();
            }
            return View(utilizador);
        }

        // POST: Utilizadors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Utilizador utilizador = db.Utilizador.Find(id);
            db.Utilizador.Remove(utilizador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ES/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ES/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ES/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <div>
        @Html.ActionLink("Lista Utilizadores", "Index", "Utilizadors");
    </div>
    <div>
        @Html.ActionLink("Lista Utilizadores", "Index", "Freguesias");
    </div>
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ES/Views/Home/Login.cshtml
@model ES_TP_EF.Utilizador

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm("Login", "Home", FormMethod.Post))
{
    //cria a tag do formulário
    @Html.AntiForgeryToken() // previne o ataque CSRF
    @Html.ValidationSummary(true)
    if (@ViewBag.Message != null)
    {
        <div style="border:1px solid red">
            @ViewBag.Message
        </div>
    }
    <table>
        <tr>
            <td>@Html.LabelFor(a => a.username)</td>
            <td>@Html.TextBoxFor(a => a.username)</td>
            <td>@Html.ValidationMessageFor(a => a.username)</td>
        </tr>
        <tr>
            <td> @Html.LabelFor(a => a.password)</td>
            <td> @Html.PasswordFor(a => a.password) </td>
            <td> @Html.ValidationMessageFor(a => a.password) </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Login" />
            </td>
            <td></td>
        </tr>
    </table>
}
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}